### ISSUE TITLE
Inbound 

### ISSUE THREAD

**Issue by ahmadreza1372** [miladrahimi/outline-bridge-server#11]
Hello dear Milad
Thanks for your repository,

I use your bridge server on Arvan cloud, every things work fine, but in Whatsapp and Telegram, voice call does not work with this bridge server, have you any idea for fix this problem ? any more config line need ?

**Comment by zol3x** [comment]
I have had the same issue but i got along.

**Comment by miladrahimi** [comment]
This tool supports both UDP and TCP protocols, so it supports video/audio calls out of the box. It might be related to your firewall settings (for example UDP traffic is blocked by UFW).
