### ISSUE TITLE
Possibility to add a release for v2fly-core v5.2.1

### ISSUE THREAD

**Issue by bestmgmt** [miladrahimi/outline-bridge-server#13]
Hi

Can you kindly add an additional release that supports `v2fly-core v.5.2.1` and has the relevant config (`JsonV5`) for it. Additionally, please add its image in `ghcr.io/getimages/v2fly-core`?

Special Thanks,

**Comment by miladrahimi** [comment]
Hi @bestmgmt, the version you've mentioned is not production-ready yet (it's a user preview version). As soon as the v2ray team release a new stable version we'd upgrade this project.
