### ISSUE TITLE
Can you please provide a little bit more details

### ISSUE THREAD

**Issue by istarkov** [miladrahimi/outline-bridge-server#17]
I'm relatively new to this, so I hope you can help clarify something for me. Is this different from a transparent proxy?

As I understand it, if there's an "Outline Client" and an "Outline Server," everything in between should use the same protocol as the Client and Server.

If the protocol hasn't changed, how can it allow anything to be bypassed?

**Comment by miladrahimi** [comment]
This is a port-forwarding tool designed for use in countries like Iran, where home and mobile internet provided by ISPs is more restricted than internet access in data centers. If you connect from home or mobile internet directly to an Outline (Shadowsocks) server, the GFW can quickly detect the server. However, connecting through a server, which is subject to less monitoring, significantly reduces the risk of detection. This tool, unlike transparent proxies, does not intercept traffic.
```
Client (home internet) <-> Bridge Server (datacenter internet) <-> Outline Server (foreign country) <-> Internet
```

**Comment by istarkov** [comment]
Thank you a lot!!! Will try in my country
