### ISSUE TITLE
Recommended bridge servers

### ISSUE THREAD

**Issue by Nicky-Sa** [miladrahimi/outline-bridge-server#18]
Hello. Thank you for your great and helpful project.
May I know which Iranian company you recommend using as the server bridge?
I used to use ArvanCloud, but it doesn't work anymore.

**Comment by miladrahimi** [comment]
Glad the tool has been useful for you!
Arvan still works fine, but you might need to switch datacenters. Arvan is great for its network quality. You can also try [Derak](https://derak.cloud), but it's not as good as Arvan in terms of speed and quality.
