### ISSUE TITLE
Whatsapp calls

### ISSUE THREAD

**Issue by Prhmma** [miladrahimi/outline-bridge-server#2]
Hey,
seems like using a bridge and an upstream server messed up with WhatsApp calls.
Is there any known fix available? I wasn't able to find anything online since normal people in the world does not have problems that we have.

Cheers;

**Comment by miladrahimi** [comment]
I've tried NGINX as tcp/udp proxy instead of v2ray, but it was worser.
Up to now, this is the best solution.
